# ndarray.T
T represents transposed array/matrix

This will return new matrix with changes.
It is member/method of ndarray.

In [8]:
import numpy as np
matrix1=np.array([[1,2,9],[2,5,4],[0,1,5]])
matrix2=matrix1.T
print("matrix 1\n\n",matrix1,"\n")
print('matrix2\n\n',matrix2,"\n")

matrix 1

 [[1 2 9]
 [2 5 4]
 [0 1 5]] 

matrix2

 [[1 2 0]
 [2 5 1]
 [9 4 5]] 



# numpy.swapaxes(array,axis1,axis2)
This function is used to interchange axis of an array.

In [12]:
matrix1=np.array([[1,2,9]])
print(matrix1)

[[1 2 9]]


In [14]:
a= np.swapaxes(matrix1,1,0)
a

array([[1],
       [2],
       [9]])

# numpy.rollaxis()
rollaxis function will roll the specified axis in backward direction until
1. specified position.
2. Syntax: numpy.rollaxis(a,axis,start=0)

In [16]:
np.rollaxis(matrix1,0,start=0)

array([[1, 2, 9]])