# NumPy

Numpy stands for Numerical Python
Numpy is python library used for working with arrays (Vectors and
Matrices).
Numpy provide functions to work with linear algebra, fourier transform and
matrices.
Numpy is a python library is partially written in python and major part is
wrriten in C language.
Array is collection of similar type data or elements.


# Creating numpy array
Numpy is used to create arrays. The array object in numpy is called
ndarray (OR) ndarray is data type or class which represent array object.
ndarray class is used to create array objects in python.
Numpy provide various functions for creating array.

### 1. array() : The function create ndarray object.
dtype: dtype is attribute of array, which define data type, the default type of
array is object.

# Numpy provide the following data types.
1. Integer data types.
a. Int8 - 1byte
b. Int16 - 2bytes
c. Int32 - 4bytes
d. Int64 - 8bytes
2. Float data types
a. Float16- 2bytes
b. Float32 - 4bytes
c. Float64 - 8bytes
3. Complex data types
a. Complex64 - 8bytes
b. Complex128 - 16bytes
4. Unsigned int data type
a. Uint8 - 1byte
b. Uint16 - 2bytes
c. Uint32 - 4bytes
d. Uint64 - 8bytes
This data types also represented using single characters.
1. i-> integer
2. f -> float
3. u -> unsigned int
4. s -> string

# Syntax of array() function:
    
array(object,dtype,order,ndim)

1. object: object is an iterable/sequence which is used to construct array.
2. dtype: this indicates datatype of array
3. order: order can be C (row-major), F(column-major)
4. ndim: This specifies minimum number of dimensions of an output array.

# Creating Array


In [168]:
import numpy as np
a=np.array([10,20,30,40])
print('array is',a,'\n')
b=np.array([[10,20],[30,40],[50,60],[70,80]])
print('array is\n' ,b,'\n')

array is [10 20 30 40] 

array is
 [[10 20]
 [30 40]
 [50 60]
 [70 80]] 



In [170]:
# Q. What is dimension?
# ans. Dimension define depth of array or nested.
# Q: What is shape of the array/
# Shape define the number of rows and columns
# Q: What is size?
# The size will define total number elements exists within array
# Q: What is dtype?
# Type of elements hold by array

In [169]:
print(b.ndim)

2


In [171]:
b.shape

(4, 2)

In [172]:
b.size

8

# Other functions of creating numpy array

# 1. empty()
This function return empty array.
2. Syntax:
1. empty(shape,dtype=float)


In [175]:
a=np.empty(shape=(2,3))
a

array([[0., 0., 0.],
       [1., 1., 0.]])

# 2.zeros()
This function return array with zero filled values.
Syntax:

    
    zeros(shape,dtype=float)

In [177]:
a=np.zeros(shape=(2,2))
a

array([[0., 0.],
       [0., 0.]])

# 3. ones()
This function return array with ones filled values.
1. Syntax:
1. ones(shape,dtype=float)

In [180]:
a=np.ones(shape=(2,2))
a

array([[1., 1.],
       [1., 1.]])

# 4. asarray()
This function return array object (OR) this function is used to convert
input object into array object.

1.  Syntax:
1.  asarray(object,dtype=None)

1. If the data type is not defined, it takes the data types based input
1. object elements types

In [182]:
b=np.asarray(a)
b

array([[1., 1.],
       [1., 1.]])

# 5. frombuffer()
1. Buffer is temp storage memory area
1. Buffers are used to increase efficiency in read and writing.
1. frombuffer() function is used to construct array object using buffer.
1.  Syntax:
1.  frombuffer(buffer,dtype=float,count=-1,offset=0)

In [185]:
buf=b'NARESHIT'
a=np.frombuffer(buf)
a

array([1.08006273e+98])

# 6 fromiter()
1. This function return numpy array object using iterator object.
1. Syntax:
1. fromiter(iterable,dtype,count=-1)
1. iterable that will provide data for one dimension array object
1. count represents the number of elements should read from iterable,
1. the default is -1 which indicates all elements.

In [191]:
lst=[n for n in range(1,11)]
a= np.fromiter(lst,dtype=np.int8)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

# 7. arange()
1. The function return array object with numeric range of values.
1. Syntax:
1. arange(start,stop,step,dtype=None)
1. start: start value of the array
1. stop: end value of the array, which is not included
1. step: difference between two values or increment or decrement value,
1. the default value is 1

In [194]:
a= np.arange(start=1,stop=11,step=2) 
a

array([1, 3, 5, 7, 9])

# 8. linspace()
1. this function works like arange function.
1. This function takes size of array. It constructs the array based on
1. number of elements. The difference between each element (step) it
1. taken based on number of elements.

In [199]:
a= np.linspace(1,5,5)
a

array([1., 2., 3., 4., 5.])

# 9. logspace()
1. The logspace function create numpy array object evenly separated
1. values using log scale.
1. Syntax:
1. logspace(start,stop,num,endpoint,base,dtype)
1. start: start specifies the start value of the interval
1. stop: specifies the stop value of/end value of the interval
1. num: The number of values to be generated within range
1. endpoint: The value of endpoint can be True or False, if endpoint is
1. True, which tells logspace include stop value, if false exclude stop
1. value.
1. base: represent base of the log space
1. dtype: the type of data hold by numpy

In [202]:
a=np.logspace(1,10)
a

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

# How to read elements from Array using indexing and slicing
1. Using index we can read only one element
1. Slicing uses multiple indexes to read more than one value
1. Using this approach we can read elements of any dimension

In [203]:
b=a[0]
b

10.0

In [205]:
b=a[0:2]
b

array([10.        , 15.26417967])

# Advanced Indexing
Using numpy advanced indexing we can read selected values from matrix
    using collection of tuples which represent row and col index. It allows to
1. read even using condition.
1. Advanced indexing is classified into two categories.
1. Integer based index
2. Boolean based index
Integer based index

# Integer based index
In integer based we try to create a collection which consist of tuples, where
each tuple represent rowindex and colindex.
Boolean