# Numpy Random

In [30]:
from numpy import random
x= random.randint(100)
x

88

In [33]:
random.rand() # it will generate number from 0 to 1

0.8976560490554659

In [37]:
x= random.randint(100, size=5) #it will generate 5 random number between 1 to 100
x

array([33, 97, 80, 29, 37])

In [42]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))
print(x)
x2= x.T

print(x2)

[[ 1 25 53 47 47]
 [79 90 61  6 86]
 [60 34 47 25 40]]
[[ 1 79 60]
 [25 90 34]
 [53 61 47]
 [47  6 25]
 [47 86 40]]


In [44]:
#Generate a 1-D array containing 5 random floats:
x = random.rand(5)

print(x)

[0.02570289 0.46920366 0.70438115 0.52611961 0.14065197]


In [45]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
x = random.rand(3, 5)

print(x)

[[0.14420649 0.0650803  0.26527353 0.1277116  0.13580591]
 [0.59633953 0.02039677 0.85851537 0.62909148 0.24446694]
 [0.17444065 0.35257973 0.47047512 0.21930332 0.60478936]]


In [46]:
x = random.choice([3, 5, 7, 9])

print(x)

3


In [47]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 5 5 3]
 [7 9 3 7 3]
 [5 7 9 9 7]]
